# Generated by Django 3.0.3 on 2020-02-11 07:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=25, null=True, unique=True)),
                ('search_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('search_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataApp.Country')),
            ],
        ),
    ]
